#include "PluginEditor.h"

VocalChainPlusAudioProcessorEditor::VocalChainPlusAudioProcessorEditor(VocalChainPlusAudioProcessor& x):AudioProcessorEditor(&x),p(x)
{
    setSize(1500,900); setResizable(true,true); setResizeLimits(1100,700,1900,1200);
    title.setText("VST3 VocalChain+",juce::dontSendNotification); title.setFont(juce::Font(34,juce::Font::bold)); title.setColour(juce::Label::textColourId,juce::Colours::white); addAndMakeVisible(title);
    subtitle.setText("by 29yuro",juce::dontSendNotification); subtitle.setColour(juce::Label::textColourId,juce::Colour(0xffb8a5ff)); addAndMakeVisible(subtitle);
    for(auto* c:{&style,&role,&key,&scale}) addAndMakeVisible(c);
    style.addItemList({"CLEAN TRAP","DARK TRAP","AIRY","DISTORTED","WIDE DOUBLES","UNDERGROUND","R&B","CUSTOM"},1); role.addItemList({"MAIN VOCAL","DOUBLES","ADLIBS"},1); key.addItemList({"Auto","C","C#","D","D#","E","F","F#","G","G#","A","A#","B"},1); scale.addItemList({"Minor","Major"},1);
    styleA=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.apvts,"style",style); roleA=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.apvts,"role",role); keyA=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.apvts,"key",key); scaleA=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.apvts,"scale",scale);
    style.onChange=[this]{p.loadPreset(style.getSelectedItemIndex());};
    for(auto* b:{&analyse,&ai,&reference}){addAndMakeVisible(b); b->setColour(juce::TextButton::buttonColourId,juce::Colour(0xff26165a));}
    for(auto* l:{&status,&pitch,&levels}){addAndMakeVisible(l);l->setColour(juce::Label::textColourId,juce::Colours::white);l->setJustificationType(juce::Justification::centredLeft);}
    status.setText("AI ASSISTANT  •  READ / ANALYSE / COACH",juce::dontSendNotification);
    analyse.onClick=[this]{timerCallback();}; ai.setClickingTogglesState(true); ai.setToggleState(true,juce::dontSendNotification);
    reference.onClick=[this]{chooser=std::make_unique<juce::FileChooser>("Choose reference song",juce::File{},"*.wav;*.mp3;*.aif;*.aiff"); auto f=juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles; chooser->launchAsync(f,[this](const juce::FileChooser& c){auto q=c.getResult();if(q.existsAsFile()){refName=q.getFileName();reference.setButtonText("REFERENCE: "+refName);} });};
    const std::pair<const char*,const char*> ks[]={{"tune","Tune"},{"comp","Comp"},{"deess","De-Esser"},{"eq","EQ"},{"sat","Saturation"},{"air","Air"},{"width","Width"},{"timing","Timing"},{"pitch","Pitch"},{"dist","Distortion"},{"filter","Filter"},{"reverb","Reverb"},{"delay","Delay"},{"delayfb","Feedback"},{"chorus","Chorus"},{"threshold","Threshold"},{"ratio","Ratio"},{"attack","Attack"},{"release","Release"},{"input","Input"},{"mix","Dry / Wet"},{"output","Output"}};
    for(auto& k:ks)addKnob(k.first,k.second); startTimerHz(8);
}
void VocalChainPlusAudioProcessorEditor::addKnob(const juce::String& id,const juce::String& name){auto k=std::make_unique<Knob>();k->s.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);k->s.setTextBoxStyle(juce::Slider::TextBoxBelow,false,60,18);k->s.setColour(juce::Slider::rotarySliderFillColourId,juce::Colour(0xff8a35ff));k->s.setColour(juce::Slider::thumbColourId,juce::Colour(0xff43e6ff));k->l.setText(name,juce::dontSendNotification);k->l.setJustificationType(juce::Justification::centred);k->l.setColour(juce::Label::textColourId,juce::Colours::white);k->a=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.apvts,id,k->s);addAndMakeVisible(k->s);addAndMakeVisible(k->l);knobs.push_back(std::move(k));}
void VocalChainPlusAudioProcessorEditor::paint(juce::Graphics& g){g.fillAll(juce::Colour(0xff060812));auto r=getLocalBounds().toFloat().reduced(14);g.setColour(juce::Colour(0xff111526));g.fillRoundedRectangle(r,14);g.setColour(juce::Colour(0xff6e2cff));g.drawRoundedRectangle(r,14,1.5f);g.setColour(juce::Colour(0xff171326));g.fillRoundedRectangle(juce::Rectangle<float>(20,125,getWidth()-40,145),10);g.setColour(juce::Colour(0xff101827));g.fillRoundedRectangle(juce::Rectangle<float>(20,285,getWidth()-40,360),10);g.setColour(juce::Colour(0xff17121f));g.fillRoundedRectangle(juce::Rectangle<float>(20,660,getWidth()-40,getHeight()-680),10);g.setColour(juce::Colour(0xff9b55ff));g.drawText("VOCAL STYLE / ROLE",35,132,260,24,juce::Justification::left);g.drawText("REFERENCE SONG",350,132,260,24,juce::Justification::left);g.drawText("AI ASSISTANT",790,132,240,24,juce::Justification::left);g.drawText("KEY & SCALE",1180,132,240,24,juce::Justification::left);g.drawText("MAIN VOCAL  •  DOUBLES  •  ADLIBS",35,294,600,28,juce::Justification::left);g.drawText("MORE EFFECTS / MIX",35,670,500,28,juce::Justification::left);}
void VocalChainPlusAudioProcessorEditor::resized(){title.setBounds(35,28,390,45);subtitle.setBounds(390,46,120,25);style.setBounds(35,165,260,36);role.setBounds(35,215,260,36);reference.setBounds(350,165,390,45);status.setBounds(790,165,350,35);analyse.setBounds(790,210,110,38);ai.setBounds(910,210,90,38);pitch.setBounds(1010,205,160,45);key.setBounds(1180,165,120,36);scale.setBounds(1310,165,130,36);levels.setBounds(1180,210,260,38);
    int x=35,y=335,w=92,h=120,gap=12; for(size_t i=0;i<knobs.size();++i){if(i==14){y=705;x=35;} if(i==19){x=1130;y=705;} knobs[i]->l.setBounds(x,y,w,20);knobs[i]->s.setBounds(x,y+20,w,h-20);x+=w+gap;if(i<14 && x+w>getWidth()-35){x=35;y+=145;}}
}
void VocalChainPlusAudioProcessorEditor::timerCallback(){float t=p.timingScore.load();juce::String s=t>80?"ON BEAT":(t>55?"SLIGHTLY OFF":"CHECK TIMING");status.setText("AI READ  •  "+s+"  "+juce::String((int)t)+"%",juce::dontSendNotification);pitch.setText("Pitch: "+p.detectedNote(),juce::dontSendNotification);levels.setText("IN "+juce::String(p.inputDb.load(),1)+" dB   OUT "+juce::String(p.outputDb.load(),1)+" dB",juce::dontSendNotification);}
